# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddData.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(715, 676)
        self.lineEditAge = QtGui.QLineEdit(Dialog)
        self.lineEditAge.setGeometry(QtCore.QRect(130, 190, 31, 20))
        self.lineEditAge.setObjectName(_fromUtf8("lineEditAge"))
        self.checkPap = QtGui.QCheckBox(Dialog)
        self.checkPap.setGeometry(QtCore.QRect(20, 290, 91, 17))
        self.checkPap.setObjectName(_fromUtf8("checkPap"))
        self.lineEditDate = QtGui.QLineEdit(Dialog)
        self.lineEditDate.setGeometry(QtCore.QRect(130, 160, 113, 20))
        self.lineEditDate.setObjectName(_fromUtf8("lineEditDate"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 341, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.checkOther = QtGui.QCheckBox(Dialog)
        self.checkOther.setGeometry(QtCore.QRect(20, 350, 70, 17))
        self.checkOther.setObjectName(_fromUtf8("checkOther"))
        self.checkChicken = QtGui.QCheckBox(Dialog)
        self.checkChicken.setGeometry(QtCore.QRect(20, 310, 101, 17))
        self.checkChicken.setObjectName(_fromUtf8("checkChicken"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 410, 671, 211))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.groupBox)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 671, 211))
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.groupBox_23 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_23.setGeometry(QtCore.QRect(0, 0, 131, 51))
        self.groupBox_23.setAutoFillBackground(True)
        self.groupBox_23.setTitle(_fromUtf8(""))
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.groupBox_15 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_15.setGeometry(QtCore.QRect(130, 0, 120, 51))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_15.setTitle(_fromUtf8(""))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.label_28 = QtGui.QLabel(self.groupBox_15)
        self.label_28.setGeometry(QtCore.QRect(30, 10, 71, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox_15)
        self.label_29.setGeometry(QtCore.QRect(30, 30, 46, 13))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_13.setGeometry(QtCore.QRect(0, 50, 671, 41))
        self.groupBox_13.setTitle(_fromUtf8(""))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.label_27 = QtGui.QLabel(self.groupBox_13)
        self.label_27.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.radioEat1 = QtGui.QRadioButton(self.groupBox_13)
        self.radioEat1.setGeometry(QtCore.QRect(190, 10, 16, 17))
        self.radioEat1.setText(_fromUtf8(""))
        self.radioEat1.setObjectName(_fromUtf8("radioEat1"))
        self.radioEat2 = QtGui.QRadioButton(self.groupBox_13)
        self.radioEat2.setGeometry(QtCore.QRect(280, 10, 16, 17))
        self.radioEat2.setText(_fromUtf8(""))
        self.radioEat2.setObjectName(_fromUtf8("radioEat2"))
        self.radioEat3 = QtGui.QRadioButton(self.groupBox_13)
        self.radioEat3.setGeometry(QtCore.QRect(370, 10, 16, 17))
        self.radioEat3.setText(_fromUtf8(""))
        self.radioEat3.setObjectName(_fromUtf8("radioEat3"))
        self.radioEat4 = QtGui.QRadioButton(self.groupBox_13)
        self.radioEat4.setGeometry(QtCore.QRect(470, 10, 16, 17))
        self.radioEat4.setText(_fromUtf8(""))
        self.radioEat4.setObjectName(_fromUtf8("radioEat4"))
        self.radioEat5 = QtGui.QRadioButton(self.groupBox_13)
        self.radioEat5.setGeometry(QtCore.QRect(590, 10, 16, 17))
        self.radioEat5.setText(_fromUtf8(""))
        self.radioEat5.setObjectName(_fromUtf8("radioEat5"))
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_14.setGeometry(QtCore.QRect(0, 90, 671, 41))
        self.groupBox_14.setTitle(_fromUtf8(""))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.label_26 = QtGui.QLabel(self.groupBox_14)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.radioMovie1 = QtGui.QRadioButton(self.groupBox_14)
        self.radioMovie1.setGeometry(QtCore.QRect(190, 10, 21, 17))
        self.radioMovie1.setText(_fromUtf8(""))
        self.radioMovie1.setObjectName(_fromUtf8("radioMovie1"))
        self.radioMovie2 = QtGui.QRadioButton(self.groupBox_14)
        self.radioMovie2.setGeometry(QtCore.QRect(280, 10, 21, 17))
        self.radioMovie2.setText(_fromUtf8(""))
        self.radioMovie2.setObjectName(_fromUtf8("radioMovie2"))
        self.radioMovie3 = QtGui.QRadioButton(self.groupBox_14)
        self.radioMovie3.setGeometry(QtCore.QRect(370, 10, 16, 17))
        self.radioMovie3.setText(_fromUtf8(""))
        self.radioMovie3.setObjectName(_fromUtf8("radioMovie3"))
        self.radioMovie4 = QtGui.QRadioButton(self.groupBox_14)
        self.radioMovie4.setGeometry(QtCore.QRect(470, 10, 21, 17))
        self.radioMovie4.setText(_fromUtf8(""))
        self.radioMovie4.setObjectName(_fromUtf8("radioMovie4"))
        self.radioMovie5 = QtGui.QRadioButton(self.groupBox_14)
        self.radioMovie5.setGeometry(QtCore.QRect(590, 10, 21, 17))
        self.radioMovie5.setText(_fromUtf8(""))
        self.radioMovie5.setObjectName(_fromUtf8("radioMovie5"))
        self.groupBox_18 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_18.setGeometry(QtCore.QRect(400, 580, 671, 41))
        self.groupBox_18.setTitle(_fromUtf8(""))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.groupBox_22 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_22.setGeometry(QtCore.QRect(250, 0, 91, 51))
        self.groupBox_22.setAutoFillBackground(True)
        self.groupBox_22.setTitle(_fromUtf8(""))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.label_36 = QtGui.QLabel(self.groupBox_22)
        self.label_36.setGeometry(QtCore.QRect(20, 10, 46, 13))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.groupBox_22)
        self.label_37.setGeometry(QtCore.QRect(20, 30, 46, 13))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.groupBox_17 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_17.setGeometry(QtCore.QRect(340, 0, 101, 51))
        self.groupBox_17.setAutoFillBackground(True)
        self.groupBox_17.setTitle(_fromUtf8(""))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.label_30 = QtGui.QLabel(self.groupBox_17)
        self.label_30.setGeometry(QtCore.QRect(30, 10, 46, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.groupBox_17)
        self.label_31.setGeometry(QtCore.QRect(30, 30, 46, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.groupBox_19 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_19.setGeometry(QtCore.QRect(440, 0, 101, 51))
        self.groupBox_19.setAutoFillBackground(True)
        self.groupBox_19.setTitle(_fromUtf8(""))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.label_32 = QtGui.QLabel(self.groupBox_19)
        self.label_32.setGeometry(QtCore.QRect(20, 10, 46, 13))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.groupBox_19)
        self.label_33.setGeometry(QtCore.QRect(30, 30, 46, 13))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.groupBox_21 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_21.setGeometry(QtCore.QRect(540, 0, 131, 51))
        self.groupBox_21.setAutoFillBackground(True)
        self.groupBox_21.setTitle(_fromUtf8(""))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.label_34 = QtGui.QLabel(self.groupBox_21)
        self.label_34.setGeometry(QtCore.QRect(30, 10, 91, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.groupBox_21)
        self.label_35.setGeometry(QtCore.QRect(30, 30, 46, 13))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(120, 0, 20, 211))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(240, 0, 20, 211))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(330, 0, 20, 211))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.groupBox)
        self.line_4.setGeometry(QtCore.QRect(430, 0, 20, 211))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.groupBox)
        self.line_5.setGeometry(QtCore.QRect(530, 0, 20, 211))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.groupBox)
        self.line_6.setGeometry(QtCore.QRect(660, 0, 20, 211))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.groupBox_20 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_20.setGeometry(QtCore.QRect(0, 130, 671, 41))
        self.groupBox_20.setTitle(_fromUtf8(""))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.radioTv5 = QtGui.QRadioButton(self.groupBox_20)
        self.radioTv5.setGeometry(QtCore.QRect(590, 10, 16, 17))
        self.radioTv5.setText(_fromUtf8(""))
        self.radioTv5.setObjectName(_fromUtf8("radioTv5"))
        self.radioTv4 = QtGui.QRadioButton(self.groupBox_20)
        self.radioTv4.setGeometry(QtCore.QRect(470, 10, 21, 17))
        self.radioTv4.setText(_fromUtf8(""))
        self.radioTv4.setObjectName(_fromUtf8("radioTv4"))
        self.radioTv3 = QtGui.QRadioButton(self.groupBox_20)
        self.radioTv3.setGeometry(QtCore.QRect(370, 10, 16, 17))
        self.radioTv3.setText(_fromUtf8(""))
        self.radioTv3.setObjectName(_fromUtf8("radioTv3"))
        self.radioTv2 = QtGui.QRadioButton(self.groupBox_20)
        self.radioTv2.setGeometry(QtCore.QRect(280, 10, 16, 17))
        self.radioTv2.setText(_fromUtf8(""))
        self.radioTv2.setObjectName(_fromUtf8("radioTv2"))
        self.radioTv1 = QtGui.QRadioButton(self.groupBox_20)
        self.radioTv1.setGeometry(QtCore.QRect(190, 10, 20, 20))
        self.radioTv1.setText(_fromUtf8(""))
        self.radioTv1.setObjectName(_fromUtf8("radioTv1"))
        self.label_25 = QtGui.QLabel(self.groupBox_20)
        self.label_25.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEditSurname = QtGui.QLineEdit(Dialog)
        self.lineEditSurname.setGeometry(QtCore.QRect(130, 70, 113, 20))
        self.lineEditSurname.setObjectName(_fromUtf8("lineEditSurname"))
        self.checkBeef = QtGui.QCheckBox(Dialog)
        self.checkBeef.setGeometry(QtCore.QRect(20, 330, 81, 17))
        self.checkBeef.setObjectName(_fromUtf8("checkBeef"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 390, 431, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 130, 81, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEditContact = QtGui.QLineEdit(Dialog)
        self.lineEditContact.setGeometry(QtCore.QRect(130, 130, 113, 20))
        self.lineEditContact.setObjectName(_fromUtf8("lineEditContact"))
        self.checkPasta = QtGui.QCheckBox(Dialog)
        self.checkPasta.setGeometry(QtCore.QRect(20, 270, 70, 17))
        self.checkPasta.setObjectName(_fromUtf8("checkPasta"))
        self.lineEditNames = QtGui.QLineEdit(Dialog)
        self.lineEditNames.setGeometry(QtCore.QRect(130, 100, 113, 20))
        self.lineEditNames.setObjectName(_fromUtf8("lineEditNames"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 190, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.submitData = QtGui.QPushButton(Dialog)
        self.submitData.setEnabled(True)
        self.submitData.setGeometry(QtCore.QRect(280, 630, 101, 41))
        self.submitData.setObjectName(_fromUtf8("submitData"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 160, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 100, 61, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.checkPizza = QtGui.QCheckBox(Dialog)
        self.checkPizza.setGeometry(QtCore.QRect(20, 250, 70, 17))
        self.checkPizza.setObjectName(_fromUtf8("checkPizza"))
        self.groupBox_16 = QtGui.QGroupBox(Dialog)
        self.groupBox_16.setGeometry(QtCore.QRect(20, 580, 671, 41))
        self.groupBox_16.setTitle(_fromUtf8(""))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.label_24 = QtGui.QLabel(self.groupBox_16)
        self.label_24.setGeometry(QtCore.QRect(0, 10, 131, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.radioRadio1 = QtGui.QRadioButton(self.groupBox_16)
        self.radioRadio1.setGeometry(QtCore.QRect(190, 10, 21, 17))
        self.radioRadio1.setText(_fromUtf8(""))
        self.radioRadio1.setObjectName(_fromUtf8("radioRadio1"))
        self.radioRadio2 = QtGui.QRadioButton(self.groupBox_16)
        self.radioRadio2.setGeometry(QtCore.QRect(280, 10, 16, 17))
        self.radioRadio2.setText(_fromUtf8(""))
        self.radioRadio2.setObjectName(_fromUtf8("radioRadio2"))
        self.radioRadio3 = QtGui.QRadioButton(self.groupBox_16)
        self.radioRadio3.setGeometry(QtCore.QRect(370, 10, 21, 17))
        self.radioRadio3.setText(_fromUtf8(""))
        self.radioRadio3.setObjectName(_fromUtf8("radioRadio3"))
        self.radioRadio4 = QtGui.QRadioButton(self.groupBox_16)
        self.radioRadio4.setGeometry(QtCore.QRect(470, 10, 16, 17))
        self.radioRadio4.setText(_fromUtf8(""))
        self.radioRadio4.setObjectName(_fromUtf8("radioRadio4"))
        self.radioRadio5 = QtGui.QRadioButton(self.groupBox_16)
        self.radioRadio5.setGeometry(QtCore.QRect(590, 10, 16, 17))
        self.radioRadio5.setText(_fromUtf8(""))
        self.radioRadio5.setObjectName(_fromUtf8("radioRadio5"))
        self.line_7 = QtGui.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(10, 410, 20, 211))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.checkPap.setText(_translate("Dialog", "Pap and Wors", None))
        self.label_3.setText(_translate("Dialog", "Surname", None))
        self.label_8.setText(_translate("Dialog", "What is your favourite food?(You can choose more than one answer)", None))
        self.checkOther.setText(_translate("Dialog", "Other", None))
        self.checkChicken.setText(_translate("Dialog", "Chicken stir fry", None))
        self.label_28.setText(_translate("Dialog", "Strongly Agree", None))
        self.label_29.setText(_translate("Dialog", "           (1)", None))
        self.label_27.setText(_translate("Dialog", "I like to eat out", None))
        self.label_26.setText(_translate("Dialog", "I like to watch movies", None))
        self.label_36.setText(_translate("Dialog", "  Agree", None))
        self.label_37.setText(_translate("Dialog", "    (2)", None))
        self.label_30.setText(_translate("Dialog", "Neutral", None))
        self.label_31.setText(_translate("Dialog", "  (3)", None))
        self.label_32.setText(_translate("Dialog", "Disagree", None))
        self.label_33.setText(_translate("Dialog", "   (4)", None))
        self.label_34.setText(_translate("Dialog", "Strongly disagree", None))
        self.label_35.setText(_translate("Dialog", "          (5)", None))
        self.label_25.setText(_translate("Dialog", "I like to watch TV", None))
        self.checkBeef.setText(_translate("Dialog", "Beef stir fry", None))
        self.label_9.setText(_translate("Dialog", "On a scale of 1 to 5 indicate whether you strongly agree to strongly disagree", None))
        self.label_5.setText(_translate("Dialog", "Contact Number", None))
        self.checkPasta.setText(_translate("Dialog", "Pasta", None))
        self.label.setText(_translate("Dialog", "Take our Survey", None))
        self.label_7.setText(_translate("Dialog", "Age", None))
        self.submitData.setText(_translate("Dialog", "Submit", None))
        self.label_2.setText(_translate("Dialog", "Personal Details:", None))
        self.label_6.setText(_translate("Dialog", "Date", None))
        self.label_4.setText(_translate("Dialog", "First Names", None))
        self.checkPizza.setText(_translate("Dialog", "Pizza", None))
        self.label_24.setText(_translate("Dialog", " I like to listen to the radio", None))

