# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewSurveyData.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(433, 339)
        self.pastaText = QtGui.QLabel(Dialog)
        self.pastaText.setGeometry(QtCore.QRect(280, 150, 31, 13))
        self.pastaText.setText(_fromUtf8(""))
        self.pastaText.setObjectName(_fromUtf8("pastaText"))
        self.maxAgeText = QtGui.QLabel(Dialog)
        self.maxAgeText.setGeometry(QtCore.QRect(280, 70, 31, 13))
        self.maxAgeText.setText(_fromUtf8(""))
        self.maxAgeText.setObjectName(_fromUtf8("maxAgeText"))
        self.label_28 = QtGui.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(320, 90, 61, 13))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_31 = QtGui.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(320, 220, 92, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 170, 216, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_26 = QtGui.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(320, 50, 69, 13))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(330, 310, 47, 13))
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(320, 30, 46, 13))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 196, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.eatText = QtGui.QLabel(Dialog)
        self.eatText.setGeometry(QtCore.QRect(280, 200, 31, 13))
        self.eatText.setText(_fromUtf8(""))
        self.eatText.setObjectName(_fromUtf8("eatText"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 66, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 130, 175, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.movieText = QtGui.QLabel(Dialog)
        self.movieText.setGeometry(QtCore.QRect(280, 220, 31, 13))
        self.movieText.setText(_fromUtf8(""))
        self.movieText.setObjectName(_fromUtf8("movieText"))
        self.label_30 = QtGui.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(320, 200, 92, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_33 = QtGui.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(320, 260, 92, 13))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(40, 240, 114, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 121, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 200, 105, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_32 = QtGui.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(320, 240, 92, 13))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.surveysText = QtGui.QLabel(Dialog)
        self.surveysText.setGeometry(QtCore.QRect(280, 30, 31, 13))
        self.surveysText.setText(_fromUtf8(""))
        self.surveysText.setObjectName(_fromUtf8("surveysText"))
        self.minAgeText = QtGui.QLabel(Dialog)
        self.minAgeText.setGeometry(QtCore.QRect(280, 90, 31, 13))
        self.minAgeText.setText(_fromUtf8(""))
        self.minAgeText.setObjectName(_fromUtf8("minAgeText"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 90, 215, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(40, 260, 154, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_27 = QtGui.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(320, 70, 49, 13))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.papText = QtGui.QLabel(Dialog)
        self.papText.setGeometry(QtCore.QRect(280, 170, 31, 13))
        self.papText.setText(_fromUtf8(""))
        self.papText.setObjectName(_fromUtf8("papText"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 220, 135, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.averageAgeText = QtGui.QLabel(Dialog)
        self.averageAgeText.setGeometry(QtCore.QRect(280, 50, 31, 13))
        self.averageAgeText.setText(_fromUtf8(""))
        self.averageAgeText.setObjectName(_fromUtf8("averageAgeText"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 150, 178, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tvText = QtGui.QLabel(Dialog)
        self.tvText.setGeometry(QtCore.QRect(280, 240, 31, 13))
        self.tvText.setText(_fromUtf8(""))
        self.tvText.setObjectName(_fromUtf8("tvText"))
        self.pizzaText = QtGui.QLabel(Dialog)
        self.pizzaText.setGeometry(QtCore.QRect(280, 130, 31, 13))
        self.pizzaText.setText(_fromUtf8(""))
        self.pizzaText.setObjectName(_fromUtf8("pizzaText"))
        self.radioText = QtGui.QLabel(Dialog)
        self.radioText.setGeometry(QtCore.QRect(280, 260, 31, 16))
        self.radioText.setText(_fromUtf8(""))
        self.radioText.setObjectName(_fromUtf8("radioText"))
        self.btOk = QtGui.QPushButton(Dialog)
        self.btOk.setGeometry(QtCore.QRect(190, 290, 75, 31))
        self.btOk.setObjectName(_fromUtf8("btOk"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_28.setText(_translate("Dialog", "#min age", None))
        self.label_31.setText(_translate("Dialog", "#average of rating", None))
        self.label_7.setText(_translate("Dialog", "Percentage of people who like Pap and wors:", None))
        self.label_26.setText(_translate("Dialog", "#average age", None))
        self.label_25.setText(_translate("Dialog", "#surveys", None))
        self.label_3.setText(_translate("Dialog", "Older person who participated in survey:", None))
        self.label_2.setText(_translate("Dialog", "Average age:", None))
        self.label_5.setText(_translate("Dialog", "Percentage of people who like Pizza:", None))
        self.label_30.setText(_translate("Dialog", "#average of rating", None))
        self.label_33.setText(_translate("Dialog", "#average of rating", None))
        self.label_11.setText(_translate("Dialog", "People like to watch TV:", None))
        self.label.setText(_translate("Dialog", "Total number of surveys:", None))
        self.label_9.setText(_translate("Dialog", "People like to eat out:", None))
        self.label_32.setText(_translate("Dialog", "#average of rating", None))
        self.label_4.setText(_translate("Dialog", "Youngest person who participated in survey:", None))
        self.label_12.setText(_translate("Dialog", "People like to listen to the radio:", None))
        self.label_27.setText(_translate("Dialog", "#max age", None))
        self.label_10.setText(_translate("Dialog", "People like to watch movies:", None))
        self.label_6.setText(_translate("Dialog", "Percentage of people who like Pasta:", None))
        self.btOk.setText(_translate("Dialog", "OK", None))

